services:
    admin.category:
        class: App\Admin\CategoriesAdmin
        arguments: [~, App\Entity\Categories, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: category }
        public: true
    admin.product:
        class: App\Admin\ProductAdmin
        arguments: [~, App\Entity\Product, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: product }
        public: true